# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3923119306193a4cc38137c4d11d3b3507dc9d5500313eef9cd7ebfe089ec6e67e5d7bab7886f129d0cd61f5c47d5f5a997cfa4abf700ce06b5faf89e0fcf857

test:
  secret_key_base: 753ddab1c9e5d08eb7b6014db757412a9e8fc75c130fcc39f17c602826dfedf53a09eaf1b1375afe959dbbdb46aff4ac3461a1f36d887765f407e9ef89091850

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
