# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 453f189b0dc1e4afbb84ce88353699ecf5a075e2a0babcee707fa67fd84a931af0adda1495a9830bc93232302fa5312e998e6448a5523b1b0fcc04af54ca51bd

test:
  secret_key_base: b7cb144fe6d8a06c27d50cccb0a1280e0d05ed9c54d27b6e05735c2240859222b6bbfce406f0d8744d9a6e048720e6532a913868f7e39b9ff2126a3ba3b8b6c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
